# Generated by Django 2.2 on 2021-11-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['id'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
