# Generated by Django 3.2 on 2021-11-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0002_auto_20211114_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Variants',
            new_name='Variant',
        ),
    ]
