# Generated by Django 3.2 on 2021-11-16 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_tests', '0004_remove_variant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_value', models.CharField(max_length=100, verbose_name='Уникальный идентификатор теста')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уникальное значение',
                'verbose_name_plural': 'Уникальные значения',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('correct_answer', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_questions', to='user_tests.question', verbose_name='Вопрос')),
                ('unique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_unique', to='user_tests.uniquevalue', verbose_name='Идентификатор теста')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_variant', to='user_tests.variant', verbose_name='')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
