# Generated by Django 3.2 on 2021-11-16 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_tests', '0005_answer_uniquevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquevalue',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_quiz', to='user_tests.quiz', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='uniquevalue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
