# Generated by Django 3.2 on 2021-11-17 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_tests', '0006_auto_20211117_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquevalue',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniquevalue',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
